/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.ants.platform.client.core;

import java.lang.Exception;
import java.lang.RuntimeException;
import java.lang.String;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class AntsPlatformClientException extends RuntimeException {
  public AntsPlatformClientException(String message) {
    super(message);
  }

  public AntsPlatformClientException(String message, Exception e) {
    super(message, e);
  }
}
