/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.ants.platform.client.core;

import java.lang.Integer;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.TimeUnit;
import java.util.function.Supplier;

public final class RequestOptions {
  private final String xAntsPlatformSdkName;

  private final String xAntsPlatformSdkVersion;

  private final String xAntsPlatformPublicKey;

  private final Optional<Integer> timeout;

  private final TimeUnit timeoutTimeUnit;

  private final Map<String, String> headers;

  private final Map<String, Supplier<String>> headerSuppliers;

  private RequestOptions(String xAntsPlatformSdkName, String xAntsPlatformSdkVersion,
      String xAntsPlatformPublicKey, Optional<Integer> timeout, TimeUnit timeoutTimeUnit,
      Map<String, String> headers, Map<String, Supplier<String>> headerSuppliers) {
    this.xAntsPlatformSdkName = xAntsPlatformSdkName;
    this.xAntsPlatformSdkVersion = xAntsPlatformSdkVersion;
    this.xAntsPlatformPublicKey = xAntsPlatformPublicKey;
    this.timeout = timeout;
    this.timeoutTimeUnit = timeoutTimeUnit;
    this.headers = headers;
    this.headerSuppliers = headerSuppliers;
  }

  public Optional<Integer> getTimeout() {
    return timeout;
  }

  public TimeUnit getTimeoutTimeUnit() {
    return timeoutTimeUnit;
  }

  public Map<String, String> getHeaders() {
    Map<String, String> headers = new HashMap<>();
    if (this.xAntsPlatformSdkName != null) {
      headers.put("X-AntsPlatform-Sdk-Name", this.xAntsPlatformSdkName);
    }
    if (this.xAntsPlatformSdkVersion != null) {
      headers.put("X-AntsPlatform-Sdk-Version", this.xAntsPlatformSdkVersion);
    }
    if (this.xAntsPlatformPublicKey != null) {
      headers.put("X-AntsPlatform-Public-Key", this.xAntsPlatformPublicKey);
    }
    headers.putAll(this.headers);
    this.headerSuppliers.forEach((key, supplier) ->  {
      headers.put(key, supplier.get());
    } );
    return headers;
  }

  public static Builder builder() {
    return new Builder();
  }

  public static final class Builder {
    private String xAntsPlatformSdkName = null;

    private String xAntsPlatformSdkVersion = null;

    private String xAntsPlatformPublicKey = null;

    private Optional<Integer> timeout = Optional.empty();

    private TimeUnit timeoutTimeUnit = TimeUnit.SECONDS;

    private final Map<String, String> headers = new HashMap<>();

    private final Map<String, Supplier<String>> headerSuppliers = new HashMap<>();

    public Builder xAntsPlatformSdkName(String xAntsPlatformSdkName) {
      this.xAntsPlatformSdkName = xAntsPlatformSdkName;
      return this;
    }

    public Builder xAntsPlatformSdkVersion(String xAntsPlatformSdkVersion) {
      this.xAntsPlatformSdkVersion = xAntsPlatformSdkVersion;
      return this;
    }

    public Builder xAntsPlatformPublicKey(String xAntsPlatformPublicKey) {
      this.xAntsPlatformPublicKey = xAntsPlatformPublicKey;
      return this;
    }

    public Builder timeout(Integer timeout) {
      this.timeout = Optional.of(timeout);
      return this;
    }

    public Builder timeout(Integer timeout, TimeUnit timeoutTimeUnit) {
      this.timeout = Optional.of(timeout);
      this.timeoutTimeUnit = timeoutTimeUnit;
      return this;
    }

    public Builder addHeader(String key, String value) {
      this.headers.put(key, value);
      return this;
    }

    public Builder addHeader(String key, Supplier<String> value) {
      this.headerSuppliers.put(key, value);
      return this;
    }

    public RequestOptions build() {
      return new RequestOptions(xAntsPlatformSdkName, xAntsPlatformSdkVersion, xAntsPlatformPublicKey, timeout, timeoutTimeUnit, headers, headerSuppliers);
    }
  }
}
