/**
 * This file was auto-generated by Fern from our API Definition.
 * Modified for SDK v3.4.0: Added agent identification support.
 */

package com.ants.platform.client;

import com.ants.platform.client.core.AgentIdGenerator;
import com.ants.platform.client.core.AntsPlatformClientApiException;
import com.ants.platform.client.core.AntsPlatformClientException;
import com.ants.platform.client.core.ClientOptions;
import com.ants.platform.client.core.MediaTypes;
import com.ants.platform.client.core.ObjectMappers;
import com.ants.platform.client.core.Suppliers;
import com.ants.platform.client.resources.projects.types.Project;
import com.ants.platform.client.resources.projects.types.Projects;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Supplier;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import com.ants.platform.client.resources.annotationqueues.AnnotationQueuesClient;
import com.ants.platform.client.resources.comments.CommentsClient;
import com.ants.platform.client.resources.datasetitems.DatasetItemsClient;
import com.ants.platform.client.resources.datasetrunitems.DatasetRunItemsClient;
import com.ants.platform.client.resources.datasets.DatasetsClient;
import com.ants.platform.client.resources.health.HealthClient;
import com.ants.platform.client.resources.ingestion.IngestionClient;
import com.ants.platform.client.resources.media.MediaClient;
import com.ants.platform.client.resources.metrics.MetricsClient;
import com.ants.platform.client.resources.models.ModelsClient;
import com.ants.platform.client.resources.observations.ObservationsClient;
import com.ants.platform.client.resources.organizations.OrganizationsClient;
import com.ants.platform.client.resources.projects.ProjectsClient;
import com.ants.platform.client.resources.prompts.PromptsClient;
import com.ants.platform.client.resources.promptversion.PromptVersionClient;
import com.ants.platform.client.resources.scim.ScimClient;
import com.ants.platform.client.resources.score.ScoreClient;
import com.ants.platform.client.resources.scoreconfigs.ScoreConfigsClient;
import com.ants.platform.client.resources.scorev2.ScoreV2Client;
import com.ants.platform.client.resources.sessions.SessionsClient;
import com.ants.platform.client.resources.trace.TraceClient;

public class AntsPlatformClient {
  private static final Logger LOGGER = Logger.getLogger(AntsPlatformClient.class.getName());

  protected final ClientOptions clientOptions;

  // SDK v3.4.0: Store public key and project ID for agent identification
  private final String publicKey;
  private String projectId;  // Made non-final to allow manual override

  protected final Supplier<AnnotationQueuesClient> annotationQueuesClient;

  protected final Supplier<CommentsClient> commentsClient;

  protected final Supplier<DatasetItemsClient> datasetItemsClient;

  protected final Supplier<DatasetRunItemsClient> datasetRunItemsClient;

  protected final Supplier<DatasetsClient> datasetsClient;

  protected final Supplier<HealthClient> healthClient;

  protected final Supplier<IngestionClient> ingestionClient;

  protected final Supplier<MediaClient> mediaClient;

  protected final Supplier<MetricsClient> metricsClient;

  protected final Supplier<ModelsClient> modelsClient;

  protected final Supplier<ObservationsClient> observationsClient;

  protected final Supplier<OrganizationsClient> organizationsClient;

  protected final Supplier<ProjectsClient> projectsClient;

  protected final Supplier<PromptVersionClient> promptVersionClient;

  protected final Supplier<PromptsClient> promptsClient;

  protected final Supplier<ScimClient> scimClient;

  protected final Supplier<ScoreConfigsClient> scoreConfigsClient;

  protected final Supplier<ScoreV2Client> scoreV2Client;

  protected final Supplier<ScoreClient> scoreClient;

  protected final Supplier<SessionsClient> sessionsClient;

  protected final Supplier<TraceClient> traceClient;

  /**
   * Legacy constructor for backward compatibility.
   */
  public AntsPlatformClient(ClientOptions clientOptions) {
    this(clientOptions, null);
  }

  /**
   * SDK v3.4.0: Constructor with public key for agent identification.
   */
  public AntsPlatformClient(ClientOptions clientOptions, String publicKey) {
    this.clientOptions = clientOptions;
    this.publicKey = publicKey;
    this.annotationQueuesClient = Suppliers.memoize(() -> new AnnotationQueuesClient(clientOptions));
    this.commentsClient = Suppliers.memoize(() -> new CommentsClient(clientOptions));
    this.datasetItemsClient = Suppliers.memoize(() -> new DatasetItemsClient(clientOptions));
    this.datasetRunItemsClient = Suppliers.memoize(() -> new DatasetRunItemsClient(clientOptions));
    this.datasetsClient = Suppliers.memoize(() -> new DatasetsClient(clientOptions));
    this.healthClient = Suppliers.memoize(() -> new HealthClient(clientOptions));
    this.ingestionClient = Suppliers.memoize(() -> new IngestionClient(clientOptions));
    this.mediaClient = Suppliers.memoize(() -> new MediaClient(clientOptions));
    this.metricsClient = Suppliers.memoize(() -> new MetricsClient(clientOptions));
    this.modelsClient = Suppliers.memoize(() -> new ModelsClient(clientOptions));
    this.observationsClient = Suppliers.memoize(() -> new ObservationsClient(clientOptions));
    this.organizationsClient = Suppliers.memoize(() -> new OrganizationsClient(clientOptions));
    this.projectsClient = Suppliers.memoize(() -> new ProjectsClient(clientOptions));
    this.promptVersionClient = Suppliers.memoize(() -> new PromptVersionClient(clientOptions));
    this.promptsClient = Suppliers.memoize(() -> new PromptsClient(clientOptions));
    this.scimClient = Suppliers.memoize(() -> new ScimClient(clientOptions));
    this.scoreConfigsClient = Suppliers.memoize(() -> new ScoreConfigsClient(clientOptions));
    this.scoreV2Client = Suppliers.memoize(() -> new ScoreV2Client(clientOptions));
    this.scoreClient = Suppliers.memoize(() -> new ScoreClient(clientOptions));
    this.sessionsClient = Suppliers.memoize(() -> new SessionsClient(clientOptions));
    this.traceClient = Suppliers.memoize(() -> new TraceClient(clientOptions));

    // SDK v3.4.0: Fetch project_id from API (matches Python/JS SDK behavior)
    // This ensures consistent agent_id generation across all SDKs
    this.projectId = fetchProjectIdFromApi();
  }

  /**
   * SDK v3.4.0: Fetch project_id from API.
   *
   * This matches the Python/JS SDK behavior where project_id is fetched from
   * the /api/public/projects endpoint, not extracted from the public key.
   *
   * The project_id from the API (e.g., "cmizlc041000bup8kxxsp2c4a") is different
   * from the UUID in the public key (e.g., "a3f78d62-92a4-4ea6-b2e4-3e0fd6088bcb").
   * Using the correct project_id ensures consistent agent_id generation across all SDKs.
   *
   * @return the project ID from API, or null if unavailable
   */
  private String fetchProjectIdFromApi() {
    try {
      // Use the already-initialized projects client to fetch project info
      ProjectsClient projectsClientInstance = new ProjectsClient(this.clientOptions);
      Projects projects = projectsClientInstance.get();

      if (projects != null && projects.getData() != null && !projects.getData().isEmpty()) {
        String projectId = projects.getData().get(0).getId();
        LOGGER.info(String.format("[PROJECT_ID] Fetched from API: %s", projectId));
        return projectId;
      }

      LOGGER.warning("[PROJECT_ID] No projects found in API response");
      return null;
    } catch (Exception e) {
      LOGGER.warning(String.format("[PROJECT_ID] Failed to fetch from API: %s", e.getMessage()));
      return null;
    }
  }

  /**
   * SDK v3.4.0: Get the project ID fetched from the API.
   *
   * This returns the actual project ID from the Ants Platform API,
   * not the UUID from the public key. This ensures consistent
   * agent_id generation across Python, JS, and Java SDKs.
   *
   * @return the project ID, or null if not available
   */
  public String getProjectId() {
    return this.projectId;
  }

  /**
   * SDK v3.4.0: Manually set the project ID.
   *
   * Use this method when the API fetch fails or when you want to explicitly
   * set the project ID. This is useful for:
   * - Environments where the API is not accessible during initialization
   * - Testing scenarios
   * - When you know the project ID in advance
   *
   * @param projectId the project ID to use for agent_id generation
   * @return this client instance for method chaining
   */
  public AntsPlatformClient setProjectId(String projectId) {
    this.projectId = projectId;
    LOGGER.info(String.format("[PROJECT_ID] Manually set to: %s", projectId));
    return this;
  }

  /**
   * SDK v3.4.0: Generate a deterministic agent ID from an agent name.
   * Uses BLAKE2b-64 hash of (agentName + projectId) to produce a 16-char hex ID.
   *
   * <p>This method handles all the complexity of agent ID generation internally:
   * <ul>
   *   <li>Extracts project_id from the public key provided during client construction</li>
   *   <li>Computes BLAKE2b-64 hash of agentName + projectId</li>
   *   <li>Returns a deterministic 16-character hex string</li>
   * </ul>
   *
   * <p>Example:
   * <pre>{@code
   * AntsPlatformClient client = AntsPlatformClient.builder()
   *     .credentials(publicKey, secretKey)
   *     .url("http://localhost:3000")
   *     .build();
   *
   * String agentId = client.generateAgentId("qa_agent");
   * // Returns: "1fdb77db0603771f" (deterministic 16-char hex)
   * }</pre>
   *
   * @param agentName the agent name (immutable identifier)
   * @return the generated agent ID (16-char hex string)
   * @throws IllegalStateException if project ID is not available
   * @throws IllegalArgumentException if agentName is null or empty
   */
  public String generateAgentId(String agentName) {
    if (this.projectId == null || this.projectId.isEmpty()) {
      throw new IllegalStateException(
          "Cannot generate agent ID: project_id not available. " +
          "The API call to fetch project_id may have failed. " +
          "Use client.setProjectId(projectId) to set it manually, " +
          "or ensure the Ants Platform server is accessible."
      );
    }
    return AgentIdGenerator.generateAgentId(agentName, this.projectId);
  }

  /**
   * SDK v3.4.0: Generate a deterministic agent ID from an agent name and project ID.
   *
   * This overload allows you to explicitly provide the project ID, which is useful when:
   * - The automatic project ID fetch failed
   * - You want to use a specific project ID
   * - You're testing with a known project ID
   *
   * @param agentName the agent name (immutable identifier)
   * @param projectId the project ID to use for agent_id generation
   * @return the generated agent ID (16-char hex string)
   * @throws IllegalArgumentException if agentName or projectId is null or empty
   */
  public String generateAgentId(String agentName, String projectId) {
    return AgentIdGenerator.generateAgentId(agentName, projectId);
  }

  // Regex pattern for validating 16-character hex agent IDs
  private static final Pattern AGENT_ID_PATTERN = Pattern.compile("^[0-9a-f]{16}$");

  /**
   * SDK v3.4.0: Updates the mutable display name for an agent.
   *
   * <p>The display name is a user-friendly label shown in the UI, while the agent ID
   * (derived from agent_name + project_id) remains immutable. This allows renaming
   * agents without breaking historical trace associations.
   *
   * <p>Example:
   * <pre>{@code
   * AntsPlatformClient client = AntsPlatformClient.builder()
   *     .credentials(publicKey, secretKey)
   *     .url("http://localhost:3000")
   *     .build();
   *
   * // Update display name using the agent's immutable ID
   * client.updateAgentDisplayName("5d15c8e8b4aee83a", "QA Agent v2.0");
   * }</pre>
   *
   * @param agentId the immutable agent identifier (16-character hex string from generateAgentId)
   * @param displayName the new UI-friendly display name for the agent
   * @return true if the update was successful, false otherwise
   * @throws IllegalArgumentException if agentId is invalid or displayName is empty/null
   */
  public boolean updateAgentDisplayName(String agentId, String displayName) {
    // Validate agentId
    if (agentId == null || agentId.isEmpty()) {
      throw new IllegalArgumentException("agentId cannot be null or empty");
    }
    if (!AGENT_ID_PATTERN.matcher(agentId).matches()) {
      throw new IllegalArgumentException(
          "agentId must be a valid 16-character hex string. Got: " + agentId);
    }

    // Validate and trim displayName
    if (displayName == null) {
      throw new IllegalArgumentException("displayName cannot be null");
    }
    String trimmedDisplayName = displayName.trim();
    if (trimmedDisplayName.isEmpty()) {
      throw new IllegalArgumentException("displayName cannot be empty or whitespace only");
    }

    // Ensure project ID is available
    if (this.projectId == null || this.projectId.isEmpty()) {
      throw new IllegalStateException(
          "Cannot update agent display name: project_id not available. " +
          "Use client.setProjectId(projectId) to set it manually.");
    }

    // Build the URL: PATCH /api/public/agents/{agentId}/display-name
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
        .addPathSegments("api/public")
        .addPathSegments("agents")
        .addPathSegment(agentId)
        .addPathSegments("display-name")
        .build();

    // Build request body (camelCase as expected by backend)
    Map<String, String> requestBody = new HashMap<>();
    requestBody.put("displayName", trimmedDisplayName);

    RequestBody body;
    try {
      body = RequestBody.create(
          ObjectMappers.JSON_MAPPER.writeValueAsBytes(requestBody),
          MediaTypes.APPLICATION_JSON);
    } catch (JsonProcessingException e) {
      LOGGER.warning(String.format(
          "[AGENT] Failed to serialize request body for agent display name update: %s",
          e.getMessage()));
      throw new AntsPlatformClientException("Failed to serialize request", e);
    }

    // Build the request with headers (PATCH method)
    Request okhttpRequest = new Request.Builder()
        .url(httpUrl)
        .method("PATCH", body)
        .headers(Headers.of(clientOptions.headers(null)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json")
        .build();

    OkHttpClient client = clientOptions.httpClient();

    try (Response response = client.newCall(okhttpRequest).execute()) {
      if (response.isSuccessful()) {
        LOGGER.info(String.format(
            "[AGENT] Successfully updated display name for agent %s to '%s'",
            agentId, trimmedDisplayName));
        return true;
      }

      ResponseBody responseBody = response.body();
      String responseBodyString = responseBody != null ? responseBody.string() : "{}";

      switch (response.code()) {
        case 401:
          LOGGER.warning(String.format(
              "[AGENT] Unauthorized: Invalid credentials for agent display name update. Agent ID: %s",
              agentId));
          break;
        case 404:
          LOGGER.warning(String.format(
              "[AGENT] Agent not found: %s. Ensure the agent exists before updating display name.",
              agentId));
          break;
        default:
          LOGGER.warning(String.format(
              "[AGENT] Failed to update agent display name. Status: %d, Response: %s",
              response.code(), responseBodyString));
      }
      return false;
    } catch (IOException e) {
      LOGGER.warning(String.format(
          "[AGENT] Network error updating agent display name: %s", e.getMessage()));
      throw new AntsPlatformClientException("Network error executing HTTP request", e);
    }
  }

  public AnnotationQueuesClient annotationQueues() {
    return this.annotationQueuesClient.get();
  }

  public CommentsClient comments() {
    return this.commentsClient.get();
  }

  public DatasetItemsClient datasetItems() {
    return this.datasetItemsClient.get();
  }

  public DatasetRunItemsClient datasetRunItems() {
    return this.datasetRunItemsClient.get();
  }

  public DatasetsClient datasets() {
    return this.datasetsClient.get();
  }

  public HealthClient health() {
    return this.healthClient.get();
  }

  public IngestionClient ingestion() {
    return this.ingestionClient.get();
  }

  public MediaClient media() {
    return this.mediaClient.get();
  }

  public MetricsClient metrics() {
    return this.metricsClient.get();
  }

  public ModelsClient models() {
    return this.modelsClient.get();
  }

  public ObservationsClient observations() {
    return this.observationsClient.get();
  }

  public OrganizationsClient organizations() {
    return this.organizationsClient.get();
  }

  public ProjectsClient projects() {
    return this.projectsClient.get();
  }

  public PromptVersionClient promptVersion() {
    return this.promptVersionClient.get();
  }

  public PromptsClient prompts() {
    return this.promptsClient.get();
  }

  public ScimClient scim() {
    return this.scimClient.get();
  }

  public ScoreConfigsClient scoreConfigs() {
    return this.scoreConfigsClient.get();
  }

  public ScoreV2Client scoreV2() {
    return this.scoreV2Client.get();
  }

  public ScoreClient score() {
    return this.scoreClient.get();
  }

  public SessionsClient sessions() {
    return this.sessionsClient.get();
  }

  public TraceClient trace() {
    return this.traceClient.get();
  }

  public static AntsPlatformClientBuilder builder() {
    return new AntsPlatformClientBuilder();
  }
}
