/**
 * This file was auto-generated by Fern from our API Definition.
 * Modified for SDK v3.4.0: Added agent identification support.
 */

package com.ants.platform.client;

import com.ants.platform.client.core.ClientOptions;
import com.ants.platform.client.core.Environment;
import java.lang.String;
import java.util.Base64;
import okhttp3.OkHttpClient;

public final class AntsPlatformClientBuilder {
  private ClientOptions.Builder clientOptionsBuilder = ClientOptions.builder();

  private String username = null;  // This is actually the public key

  private String password = null;  // This is actually the secret key

  private String xAntsPlatformSdkName = null;

  private String xAntsPlatformSdkVersion = null;

  private String xAntsPlatformPublicKey = null;

  private Environment environment;

  // SDK v3.4.0: Store public key for project_id extraction
  private String publicKey = null;

  public AntsPlatformClientBuilder credentials(String username, String password) {
    this.username = username;
    this.password = password;
    // SDK v3.4.0: Store public key for project_id extraction
    this.publicKey = username;
    return this;
  }

  /**
   * Sets xAntsPlatformSdkName
   */
  public AntsPlatformClientBuilder xAntsPlatformSdkName(String xAntsPlatformSdkName) {
    this.xAntsPlatformSdkName = xAntsPlatformSdkName;
    return this;
  }

  /**
   * Sets xAntsPlatformSdkVersion
   */
  public AntsPlatformClientBuilder xAntsPlatformSdkVersion(String xAntsPlatformSdkVersion) {
    this.xAntsPlatformSdkVersion = xAntsPlatformSdkVersion;
    return this;
  }

  /**
   * Sets xAntsPlatformPublicKey
   */
  public AntsPlatformClientBuilder xAntsPlatformPublicKey(String xAntsPlatformPublicKey) {
    this.xAntsPlatformPublicKey = xAntsPlatformPublicKey;
    return this;
  }

  public AntsPlatformClientBuilder url(String url) {
    this.environment = Environment.custom(url);
    return this;
  }

  /**
   * Sets the timeout (in seconds) for the client
   */
  public AntsPlatformClientBuilder timeout(int timeout) {
    this.clientOptionsBuilder.timeout(timeout);
    return this;
  }

  /**
   * Sets the underlying OkHttp client
   */
  public AntsPlatformClientBuilder httpClient(OkHttpClient httpClient) {
    this.clientOptionsBuilder.httpClient(httpClient);
    return this;
  }

  public AntsPlatformClient build() {
    String unencodedToken = username + ":" + password;
    String encodedToken = Base64.getEncoder().encodeToString(unencodedToken.getBytes());
    this.clientOptionsBuilder.addHeader("Authorization", "Basic " + encodedToken);
    if (xAntsPlatformSdkName != null) {
      this.clientOptionsBuilder.addHeader("X-AntsPlatform-Sdk-Name", this.xAntsPlatformSdkName);
    }
    if (xAntsPlatformSdkVersion != null) {
      this.clientOptionsBuilder.addHeader("X-AntsPlatform-Sdk-Version", this.xAntsPlatformSdkVersion);
    }
    if (xAntsPlatformPublicKey != null) {
      this.clientOptionsBuilder.addHeader("X-AntsPlatform-Public-Key", this.xAntsPlatformPublicKey);
    }
    clientOptionsBuilder.environment(this.environment);
    // SDK v3.4.0: Pass public key to client for agent ID generation
    return new AntsPlatformClient(clientOptionsBuilder.build(), this.publicKey);
  }
}
