/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.ants.platform.client.resources.health.errors;

import com.ants.platform.client.core.AntsPlatformClientApiException;
import java.lang.Object;

public final class ServiceUnavailableError extends AntsPlatformClientApiException {
  public ServiceUnavailableError(Object body) {
    super("ServiceUnavailableError", 503, body);
  }
}
