/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.ants.platform.client.resources.ingestion.types;

import java.lang.String;
import java.util.Optional;

public interface ICreateEventBody extends IOptionalObservationBody {
  Optional<String> getId();
}
