/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.ants.platform.client.resources.ingestion.types;

import java.time.OffsetDateTime;
import java.util.Optional;

public interface IUpdateSpanBody extends IUpdateEventBody {
  Optional<OffsetDateTime> getEndTime();
}
