/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.ants.platform.client.resources.metrics;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.ants.platform.client.core.ClientOptions;
import com.ants.platform.client.core.AntsPlatformClientApiException;
import com.ants.platform.client.core.AntsPlatformClientException;
import com.ants.platform.client.core.ObjectMappers;
import com.ants.platform.client.core.QueryStringMapper;
import com.ants.platform.client.core.RequestOptions;
import java.io.IOException;
import java.lang.Object;
import java.lang.String;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import com.ants.platform.client.resources.commons.errors.AccessDeniedError;
import com.ants.platform.client.resources.commons.errors.Error;
import com.ants.platform.client.resources.commons.errors.MethodNotAllowedError;
import com.ants.platform.client.resources.commons.errors.NotFoundError;
import com.ants.platform.client.resources.commons.errors.UnauthorizedError;
import com.ants.platform.client.resources.metrics.requests.GetMetricsRequest;
import com.ants.platform.client.resources.metrics.types.MetricsResponse;

public class MetricsClient {
  protected final ClientOptions clientOptions;

  public MetricsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Get metrics from the ANTS Platform project using a query object
   */
  public MetricsResponse metrics(GetMetricsRequest request) {
    return metrics(request,null);
  }

  /**
   * Get metrics from the ANTS Platform project using a query object
   */
  public MetricsResponse metrics(GetMetricsRequest request, RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()
      .addPathSegments("api/public")
      .addPathSegments("metrics");QueryStringMapper.addQueryParameter(httpUrl, "query", request.getQuery(), false);
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Content-Type", "application/json")
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        if (response.isSuccessful()) {
          return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), MetricsResponse.class);
        }
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        try {
          switch (response.code()) {
            case 400:throw new Error(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
            case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
            case 403:throw new AccessDeniedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
            case 404:throw new NotFoundError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
            case 405:throw new MethodNotAllowedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        throw new AntsPlatformClientApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class));
      }
      catch (IOException e) {
        throw new AntsPlatformClientException("Network error executing HTTP request", e);
      }
    }
  }
